language: rust

rust:
  - nightly
  - beta
  - stable

cache: cargo

before_script:
  - rustup component add clippy

script:
  - cargo test --all-features --verbose
  - cargo clippy --all-features -- -Dwarnings

matrix:
  allow_failures:
    - rust: nightly
