language: rust

rust:
  - nightly
  - beta
  - stable

cache: cargo

before_script:
  - rustup component add clippy

script:
  - cargo test --verbose
  - cargo clippy -- -Dwarnings

matrix:
  allow_failures:
    - rust: nightly
